name: Build and Push

on:
  push:
    branches: 
      - main
      - main-thesis
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Build develop image
        run: make build.develop
      - name: Run lint
        run: ./scripts/develop.sh make fmt
      - name: Run unit test
        run: ./scripts/develop.sh make test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build runtime image
        run: make build
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo $VERSION

          DOCKER_IMAGE=${{ secrets.DOCKER_USER }}/${GITHUB_REPOSITORY#*/}

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          docker tag ${{ DOCKER_IMAGE }}:latest ${{ env.IMAGE_NAME }}:$VERSION
          docker push ${{ DOCKER_IMAGE }}:$VERSION
